export const TRIVIA_FACTS: string[] = [
  // Original facts
  'The Beatles have sold over 600 million records worldwide — more than any other artist.',
  "Michael Jackson's 'Thriller' is the best-selling album of all time with over 70 million copies sold.",
  "Queen's 'Bohemian Rhapsody' spent nine weeks at number one in the UK when first released in 1975.",
  'The guitar has existed in some form for over 4,000 years, tracing back to ancient Mesopotamia.',
  'Stevie Wonder was signed to Motown Records at age 11 and had his first top 40 hit at 12.',
  "Beyoncé's 'Lemonade' (2016) became the fastest-selling album in iTunes history at the time.",
  "The word 'jazz' first appeared in print in 1913 in the San Francisco Bulletin.",
  "Led Zeppelin's 'Stairway to Heaven' is one of the most-requested songs in radio history despite never being released as a single.",
  "Elton John has written a new song every day for over 50 years — he estimates he has thousands of unrecorded demos.",
  "Whitney Houston's version of 'I Will Always Love You' spent 14 weeks at number one in the US.",
  "Mariah Carey's 'All I Want for Christmas Is You' re-enters the charts every December and first hit number one on the Billboard Hot 100 in 2019 — 25 years after its release.",
  "The London Symphony Orchestra has recorded the music for more Hollywood blockbusters than any other orchestra.",
  "AC/DC's 'Back in Black' is the second best-selling album of all time, after 'Thriller'.",
  "David Bowie created 27 studio albums spanning five decades, constantly reinventing his sound.",
  'Jimi Hendrix was largely self-taught and could not read music.',
  "The 'Happy Birthday to You' song was composed in 1893 and was in copyright until 2016.",
  "Pink Floyd's 'Dark Side of the Moon' remained on the Billboard 200 chart for a record 937 weeks.",
  "Adele's '21' is the best-selling album of the 21st century so far in the UK.",
  'Elvis Presley never performed outside North America after his famous 1973 Aloha from Hawaii concert.',
  "The Rolling Stones took their name from a Muddy Waters song: 'Rollin' Stone'.",
  "Prince recorded and released 39 studio albums in his lifetime — but reportedly had hundreds more in his famous vault.",
  "Daft Punk recorded 'Get Lucky' in just one take.",
  "The theremin — played without being touched — was invented by Russian physicist Léon Theremin in 1920.",
  "Celine Dion was the first Canadian artist to have a gold record in France.",
  "ABBA turned down a $1 billion offer to reunite for a world tour in 2000.",
  'The first music video to be played on MTV was "Video Killed the Radio Star" by The Buggles on 1 August 1981.',
  "Eminem holds the Guinness World Record for most words in a hit single: 1,560 words in 'Rap God'.",
  "The harmonica is the world's best-selling musical instrument.",
  "Nirvana's 'Nevermind' knocked Michael Jackson's 'Dangerous' off the top of the Billboard chart in 1992.",
  "Taylor Swift re-recorded her first six albums to reclaim ownership of her master recordings.",
  "Freddie Mercury wrote 'Crazy Little Thing Called Love' in the bath — and recorded it the same day.",
  'The steel drum was invented in Trinidad in the 1930s and is the only acoustic instrument invented in the 20th century.',
  "Frank Sinatra's 'My Way' has been covered more than any other song in history.",
  "Bruce Springsteen performed a four-hour concert in Helsinki in 2012 — one of the longest rock sets on record.",
  "Radiohead made 'In Rainbows' available on a pay-what-you-want basis in 2007 — and made more money than from their previous album.",
  "The first ever Grammy Award for Best Rap Album was given to DJ Jazzy Jeff & The Fresh Prince in 1989.",
  "Dolly Parton wrote 'I Will Always Love You' and 'Jolene' on the same day.",
  "Bob Dylan was the first musician to win the Nobel Prize in Literature, awarded in 2016.",
  "The Grateful Dead performed over 2,300 live concerts — more than almost any other rock band.",
  "Aretha Franklin was the first woman inducted into the Rock and Roll Hall of Fame in 1987.",
  "The bass line of 'Under Pressure' by Queen and David Bowie was so recognizable that Vanilla Ice sampled it — and claimed it was different because he added a note.",
  "The theremin was used to create the eerie sounds in the original 'Star Trek' theme.",
  "Chuck Berry's 'Johnny B. Goode' was included on the Voyager Golden Record launched into space in 1977.",
  "The record for the most number one singles in the UK belongs to Elvis Presley with 21.",
  "Motown was founded by Berry Gordy Jr. with an $800 loan from his family in 1959.",
  "Kate Bush was the first woman to debut at number one in the UK charts with her first single, 'Wuthering Heights' (1978).",
  "Kendrick Lamar's 'DAMN.' became the first hip-hop album to win the Pulitzer Prize for Music in 2018.",
  "The average pop song is 3 minutes 30 seconds — a standard set by the original 78 rpm vinyl format.",
  "Amy Winehouse's 'Back to Black' is one of the best-selling albums in UK chart history.",
  "The longest commercially released song is 'The Devil Glitch' by Chris Butler, clocking in at 69 minutes.",

  // Song origins and writing stories
  "'Yesterday' by The Beatles is the most covered song in history, with over 2,200 recorded versions.",
  "John Lennon and Paul McCartney first met at a church fete in Woolton, Liverpool in July 1957.",
  "Freddie Mercury's real name was Farrokh Bulsara.",
  "Bob Dylan's real name is Robert Allen Zimmerman.",
  "'Bohemian Rhapsody' was initially opposed by Queen's record label, who thought it was too long for radio play.",
  "'Hotel California' by the Eagles has famously never been officially explained by the band.",
  "'Total Eclipse of the Heart' was written by Jim Steinman as a love song for a vampire musical.",
  "Billy Joel's 'Piano Man' is autobiographical — he worked as a piano bar performer in Los Angeles in 1972.",
  "Nirvana's 'Smells Like Teen Spirit' was named after a deodorant brand worn by Kurt Cobain's then-girlfriend.",
  "Aretha Franklin's 'Respect' was originally written and recorded by Otis Redding in 1965.",
  "The song 'Killing Me Softly' was written after singer-songwriter Lori Lieberman watched Don McLean perform live.",
  "Brian Eno invented ambient music after a car accident left him bedridden and unable to turn down a record player.",
  "Johnny Cash wore black as a statement — his song 'Man in Black' explains it as solidarity with the poor and imprisoned.",
  "'Creep' by Radiohead was deleted as a single in the UK after flopping, then became an international hit.",
  "Iggy Pop co-wrote 'Lust for Life' in 15 minutes in a Berlin hotel room with David Bowie.",
  "Johnny Cash recorded 'Hurt' at age 71 — it was originally written by Trent Reznor of Nine Inch Nails.",
  "The Beatles' 'Come Together' was written by John Lennon as a campaign song for Timothy Leary's California gubernatorial run.",
  "The Doors got their name from Aldous Huxley's book 'The Doors of Perception.'",
  "R.E.M.'s 'Losing My Religion' refers to Southern US slang for losing one's temper — it is not about religion.",
  "Radiohead's band name comes from a Talking Heads song.",
  "'Purple Rain' was performed live in one take for the film's recording.",
  "Lorde wrote 'Royals' at age 16, inspired by how mainstream pop music didn't reflect her New Zealand teenage life.",
  "The Bee Gees wrote and produced most of the Saturday Night Fever soundtrack in under five days.",
  "Fleetwood Mac recorded 'Rumours' while two couples in the band were simultaneously breaking up.",
  "The Rolling Stones' 'Exile on Main St.' was recorded in the basement of Keith Richards' rented French villa.",
  "Paul Simon's 'Graceland' was recorded in South Africa during apartheid, sparking both controversy and celebration of African music.",
  "Billie Holiday recorded 'Strange Fruit' in 1939 after her label refused — she released it on an independent label instead.",
  "The song 'Barbie Girl' by Aqua led to a Mattel lawsuit; the judge dismissed it and advised both parties to 'chill.'",
  "N.W.A's 'Straight Outta Compton' sold on word of mouth alone with no radio play and no promotional budget.",
  "'Gangnam Style' by Psy was the first YouTube video to reach 1 billion views.",
  "Lady Gaga co-wrote 'The Edge of Glory' in one night after her grandfather passed away.",
  "The US National Anthem 'The Star-Spangled Banner' was set to the tune of a popular English drinking song.",
  "Radiohead's 'Creep' shares credits with Albert Hammond and Mike Hazlewood after its similarity to their song 'The Air That I Breathe' was recognised.",

  // Artist biographical oddities
  "Jimi Hendrix played a right-handed Fender Stratocaster flipped upside down and restrung for left-handed playing.",
  "David Bowie's eyes appeared to be different colours due to anisocoria — one pupil was permanently dilated from a teenage fight.",
  "Ringo Starr's real name is Richard Starkey.",
  "Elvis Costello's real name is Declan MacManus.",
  "Prince could play over 27 instruments.",
  "Elton John wore over 4,000 different pairs of glasses throughout his career.",
  "Kanye West dropped out of college to pursue music — directly inspiring his debut album 'The College Dropout.'",
  "Michael Jackson's moonwalk was first performed on television on 25 March 1983, during the Motown 25 special.",
  "Sia wrote hits for Rihanna ('Diamonds'), Beyoncé ('Pretty Hurts'), and David Guetta ('Titanium') before achieving solo fame.",
  "Brian Wilson of The Beach Boys produced 'Pet Sounds' almost entirely without the rest of the band present.",
  "The original Woodstock festival in 1969 drew over 400,000 people, far exceeding its intended capacity.",
  "Marvin Gaye's 'What's Going On' was initially rejected by Motown before becoming one of the label's best-selling singles.",
  "Nina Simone trained as a classical pianist before becoming a jazz and soul icon.",
  "Ozzy Osbourne bit the head off a live bat on stage in 1982, thinking it was a rubber toy thrown by a fan.",
  "Louis Armstrong played trumpet with such force he developed calluses inside his lips.",
  "Kurt Cobain was ranked among the greatest guitarists of all time despite calling himself a mediocre musician.",
  "Tina Turner performed a record-breaking world tour in 1987–88, grossing over $70 million.",
  "Daft Punk maintained their robot helmet personas in all public appearances for decades to keep focus on the music.",
  "Run-D.M.C. were the first rap group on the cover of Rolling Stone magazine.",
  "Snoop Dogg was discovered by Dr. Dre after appearing on a mix tape.",
  "Brian Eno observed that the Velvet Underground's debut album barely sold, but everyone who bought it started a band.",
  "Lizzo played a crystal flute at a 2022 Washington D.C. concert — the flute had belonged to US President James Madison.",
  "Adele named all her albums after her age at the time of release: 19, 21, 25, and 30.",
  "Billie Eilish became the first artist born in the 2000s to have a number one album in the US.",
  "Michael Jackson's anti-gravity lean in the 'Smooth Criminal' video was achieved via special shoes with a heel slot.",
  "Rod Stewart drew an estimated 3.5 million people to a free New Year's Eve concert in Rio de Janeiro in 1994.",
  "Cardi B became the first solo female rapper to have a diamond-certified single with 'Bodak Yellow.'",
  "Ed Sheeran performs all his live concerts as a solo act, building up his entire sound live using only a loop pedal.",
  "Coldplay have sold over 100 million records worldwide.",
  "Mariah Carey claims a five-octave vocal range.",
  "Pharrell Williams' 'Happy' was certified diamond in the US — the fastest song to reach that milestone at the time.",

  // Chart records and sales milestones
  "Guns N' Roses' 'Appetite for Destruction' is the best-selling debut album of all time in the United States.",
  "Shania Twain's 'Come On Over' is the best-selling country album of all time and the best-selling album by a female artist.",
  "Miles Davis' 'Kind of Blue' is the best-selling jazz album of all time.",
  "Metallica has sold over 125 million albums worldwide, making them the best-selling heavy metal band of all time.",
  "Bob Marley's 'Legend' is the best-selling reggae album of all time.",
  "Eminem has sold over 220 million records worldwide, making him the best-selling rap artist in history.",
  "The Spice Girls have sold over 100 million records worldwide, making them the best-selling female group of all time.",
  "Norah Jones sold 27 million copies of her debut album 'Come Away with Me,' one of the best-selling debuts ever.",
  "Drake holds the record for the most entries on the Billboard Hot 100, with over 250 charted songs.",
  "Katy Perry became the first artist to have five number one singles from a single album with 'Teenage Dream.'",
  "Whitney Houston had seven consecutive number one singles on the Billboard Hot 100 between 1985 and 1988.",
  "'American Pie' by Don McLean runs 8 minutes 42 seconds — one of the longest songs ever to reach number one.",
  "Fleetwood Mac's 'Rumours' has spent over 450 weeks on the Billboard 200 across multiple chart runs.",
  "Taylor Swift broke a record in 2022 when her album 'Midnights' occupied all top ten spots on the Hot 100 simultaneously.",
  "Nas' 'Illmatic' is widely considered the greatest hip-hop debut album ever made.",
  "Macklemore & Ryan Lewis won the Grammy for Best Rap Album over Kendrick Lamar in 2014, widely regarded as one of the biggest upsets in Grammy history.",
  "Hip-hop surpassed rock as the best-selling music genre in the United States in 2017.",
  "'Ice Ice Baby' by Vanilla Ice was the first rap single to reach number one on the Billboard Hot 100, in 1990.",
  "Run-D.M.C.'s collaboration with Aerosmith on 'Walk This Way' is credited with bridging hip-hop and rock audiences.",
  "Michael Jackson's 'Thriller' video cost $500,000 to produce — a record for a music video at the time.",
  "The first platinum record was awarded to the Eagles for 'Their Greatest Hits (1971–1975)' in 1976.",
  "Billy Joel's '52nd Street' was the first commercially released CD, launched in Japan in October 1982.",
  "'Mr. Brightside' by The Killers has spent more cumulative weeks on the UK Singles Chart than any other song.",
  "The Chainsmokers' 'Closer' spent 12 weeks at number one on the Billboard Hot 100.",
  "Snoop Dogg's 'Doggystyle' sold over 800,000 copies in its first week — a record for a debut rap album at the time.",
  "DJ Kool Herc is credited with inventing hip-hop at a back-to-school party in the Bronx in August 1973.",

  // Industry firsts and awards
  "The first Grammy Awards ceremony was held in May 1959.",
  "The Beastie Boys were the first rap group to have a number one album on the Billboard 200, with their debut 'Licensed to Ill' in 1986.",
  "Sam Smith won the Oscar, Golden Globe, Grammy, and BRIT Award for 'Writing's on the Wall' from the James Bond film Spectre.",
  "Childish Gambino's 'This Is America' debuted at number one on the Billboard Hot 100 in 2018.",
  "Michael Jackson's 1993 Super Bowl halftime show was the first to feature a major pop act as the sole headliner, transforming the format.",
  "The first music to be played in space was 'Jingle Bells,' performed by astronauts on Gemini 6 in December 1965.",
  "Nine Inch Nails' Trent Reznor won the Academy Award for Best Original Score for 'The Social Network' in 2011.",
  "Madonna's 'Vogue' brought the underground ballroom culture of Harlem's Black and Latino LGBTQ+ community to mainstream audiences in 1990.",
  "The most sampled recording in history is 'Amen, Brother' by The Winstons — specifically a six-second drum break known as the Amen Break.",
  "'Weird Al' Yankovic has charted a top-10 album in every decade since the 1980s — the only comedy artist to achieve this.",

  // Instrument history and facts
  "The piano has over 12,000 individual parts.",
  "The piano was originally called the 'pianoforte,' meaning 'soft-loud' in Italian.",
  "The saxophone is classified as a woodwind instrument despite being made of brass.",
  "The flute is the only woodwind instrument that does not use a reed.",
  "The oboe is used to tune the orchestra at the start of concerts because its pitch is the most stable.",
  "The violin family — violin, viola, cello, and double bass — emerged in 16th-century Italy.",
  "The saxophone was invented by Adolphe Sax in Brussels in the 1840s.",
  "The ukulele originated in Hawaii as an adaptation of Portuguese instruments brought by immigrants in the 1880s.",
  "The banjo originated in West Africa and was brought to the Americas by enslaved Africans.",
  "The first Moog synthesizer was built by Robert Moog in 1964, revolutionizing recorded music.",
  "The accordion was invented in Vienna in 1829.",
  "The didgeridoo is one of the world's oldest wind instruments, played by Indigenous Australians for over 1,500 years.",
  "The bassoon is the largest woodwind instrument in a standard orchestra.",
  "The electric guitar was invented in the early 1930s to project sound above loud brass sections in big bands.",
  "The drum kit emerged around 1918 when the invention of the bass drum pedal allowed one person to play multiple drums.",
  "The Gibson Les Paul was co-designed with jazz guitarist Les Paul and introduced in 1952.",
  "The Fender Stratocaster was introduced in 1954 and remains one of the most iconic guitar designs in history.",
  "The fiddle and violin are the same instrument — the difference is entirely in the style of music played.",
  "The clavichord is one of the earliest keyboard instruments, predating the piano by several centuries.",
  "The sitar became popular in Western music after George Harrison learned to play it from Indian musician Ravi Shankar.",
  "The oldest known musical instrument is a flute carved from a cave bear bone, estimated to be 60,000 years old.",
  "The oldest surviving musical notation dates to ancient Sumer, around 2000 BC.",

  // Genre history
  "The Ramones are widely credited as the godfathers of punk rock.",
  "James Brown's rhythmic innovations made him one of the most sampled artists in music history.",
  "Kraftwerk pioneered electronic music and directly influenced the development of techno, house, hip-hop, and synth-pop.",
  "The term 'rock and roll' originally appeared in African American slang and was later popularized as a genre name by DJ Alan Freed.",
  "The first major outdoor rock festival was the Monterey Pop Festival in California in 1967.",
  "Miles Davis' 'Bitches Brew' in 1970 pioneered jazz fusion, blending jazz improvisation with rock amplification.",
  "The first hip-hop record ever pressed was 'Rapper's Delight' by the Sugarhill Gang in 1979.",
  "Green Day's 'American Idiot' introduced millions of younger listeners to punk rock when it was released in 2004.",

  // Classical
  "Mozart composed his first symphony at age eight.",
  "Beethoven was completely deaf when he composed his Ninth Symphony.",
]

/** Fisher-Yates in-place shuffle; returns the same array for chaining. */
export function shuffle<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}
